def build_2class_prompt():
    prompt = (
    "A conversation between User and Assistant.\n\n"
    "The Assistant first thinks in <think>…</think> tags then answers in one word (Human or AI) in <answer>…</answer> tags.\n\n"
    "Your task: You are given a human-written or AI-generated/edited piece of text. You must determine whether the piece was written/edited by AI or human-written.\n"
    "Let's think step-by-step. Describe inconsistencies/AI artifacts or any clues that this text may be human/written, summarize your analysis, then answer with Human or AI."
)
    return prompt

def build_3class_prompt():
    prompt = (
    "A conversation between User and Assistant.\n\n"
    "The Assistant first thinks in <think>…</think> tags then answers with one label (AI, Polish, or Human) in <answer>…</answer> tags.\n\n"
    "Your task: You are given a piece of text that may be originally written by a human, generated by an AI, or written by a human and later polished by an AI.\n\n"
    "Label definitions:\n"
    "- Human: entirely human-written with no AI assistance.\n"
    "- AI: fully generated by an AI.\n"
    "- Polish: originally human-written but subsequently edited, refined, or polished by an AI.\n\n"
    "Let's think step-by-step. Describe inconsistencies, AI artifacts, or any clues indicating whether the text is Human, Polish, or AI. Summarize your analysis, then answer with exactly one of the labels: Human, Polish, or AI."
)
    return prompt

def build_4class_prompt():
    prompt = (
    "A conversation between User and Assistant.\n\n"
    "The Assistant first thinks in <think>…</think> tags then answers with one label (AI, Polish, Human, or Meaningless) in <answer>…</answer> tags.\n\n"
    "Your task: You are given a piece of text that may be originally written by a human, generated by an AI, written by a human and polished by AI, or completely meaningless.\n\n"
    "Label definitions:\n"
    "- Human: entirely human-written with no AI assistance.\n"
    "- AI: fully generated by an AI.\n"
    "- Polish: originally human-written but subsequently edited, refined, or polished by an AI.\n"
    "- Meaningless: text that is incoherent, structurally collapsed, or contains repetitive loops/gibberish.\n\n"
    "Let's think step-by-step. Describe inconsistencies, AI artifacts, repetition patterns, or any clues indicating the source. Summarize your analysis, then answer with exactly one of the labels: Human, Polish, AI, or Meaningless."
)
    return prompt

def build_2class_cot_prompt(text, label):
    prompt = f"""You're a forensic writing analyst trained to detect whether a piece of text was written by a human or generated by AI.

Below is a passage of text and a known label indicating whether it is Human-written or AI-generated.

Your job is to:
1. Analyze the text step by step.
2. Identify concrete evidence that supports the given label.
3. Contrast it with why the opposite label is less likely.
4. Write your reasoning in natural language inside <think> tags.
5. Conclude with the final label (One word: "Human" or "AI") in <answer> tags.
6. Do not use any other tags or formatting.
7. Do not explicitly mention the ground truth label in your reasoning. Assume you do not yet know the label.

Always ground your analysis in specific stylistic, structural, or semantic features of the text. Avoid generic summaries or descriptions.

---

Text:
"{text}"

Ground Truth Label:
{label}

<think>"""
    return prompt

def build_3class_cot_prompt(text, label):
    prompt = f"""You are a forensic writing analyst specialized in distinguishing between three types of text sources:
1. **Human**: Written entirely by a human, often containing natural irregularities, distinct voice, or minor imperfections.
2. **AI**: Generated entirely by an AI model, typically characterized by uniform structure, generic tone, and lack of deep specific intent.
3. **Polish**: Originally written by a human but refined or rewritten by an AI tools. This category usually combines human-like logic and specific details with the perfect grammar and smooth flow typical of AI.

Below is a passage of text and a known label indicating its source.

Your job is to:
1. Analyze the text's style, structure, and semantics step by step.
2. Identify concrete evidence that supports the given **Ground Truth Label**.
3. Explicitly contrast this with why the other two categories are less likely.
   - *Example: If the label is "Polish", explain why it looks too smooth to be raw "Human" but too specific/structured to be raw "AI".*
4. Write your reasoning in natural language inside <think> tags.
5. Conclude with the final label (One word: "Human", "AI", or "Polish") in <answer> tags.
6. Do not explicitly mention the ground truth label in your reasoning (e.g., do not say "Since the label is AI..."). Instead, derive the conclusion from the text features.

---

Text:
"{text}"

Ground Truth Label:
{label}

<think>"""
    return prompt

def build_4class_cot_prompt(text, label):
    prompt = f"""You are a forensic writing analyst specialized in distinguishing between four types of text sources:

1. **Human**: Written entirely by a human, often containing natural irregularities, distinct voice, minor imperfections, or colloquialisms.
2. **AI**: Generated entirely by an AI model, typically characterized by uniform structure, generic tone, excessive politeness, and a lack of deep specific intent.
3. **Polish**: Originally written by a human but refined or rewritten by an AI tool. This category usually combines human-like logic and specific details with the perfect grammar, smooth flow, and "standardized" vocabulary typical of AI.
4. **Meaningless**: Text that is incoherent, structurally collapsed, or semantically void. Characteristics include endless repetition loops (e.g., "I am I am I am"), gibberish, encoding errors (mojibake), random symbols, or complete lack of logical flow that fails to convey information.

Below is a passage of text and a known label indicating its source.

Your job is to:
1. Analyze the text's style, structure, and semantics step by step.
2. Identify concrete evidence that supports the given **Ground Truth Label**.
3. Explicitly contrast this with why the other three categories are less likely.
   - *Example (Polish): Explain why it looks too smooth to be raw "Human" but too specific to be raw "AI".*
   - *Example (Meaningless): Explain that the text lacks the basic communicative intent found in "Human" or "AI" writing due to its broken structure or infinite loops.*
4. Write your reasoning in natural language inside <think> tags.
5. Conclude with the final label (One word: "Human", "AI", "Polish", or "Meaningless") in <answer> tags.
6. Do not explicitly mention the ground truth label in your reasoning (e.g., do not say "Since the label is Meaningless..."). Instead, derive the conclusion from the observed text features.

---

Text:
"{text}"

Ground Truth Label:
{label}

<think>"""
    return prompt

def build_2class_eval_prompt():
    prompt = """You are an expert evaluator tasked with assessing whether a model’s final classification is consistent with its reasoning. The model's objective is to determine whether a given piece of text was written by a human or generated by a large language model (LLM).

You will be provided with:

- An input text: the passage under evaluation.
- A reasoning trace, enclosed in <think>...</think> tags, representing the model's chain-of-thought.
- A final classification, enclosed in <answer>...</answer> tags, indicating the model’s predicted label (Human or AI).

Your task is to return a list of three float scores, each ranging from 0.0 to 1.0, corresponding to the following criteria:

1. Answer–Reasoning Alignment: Does the reasoning logically support the final answer? This should be binary (1.0 or 0.0) based on whether the reasoning is consistent with the final classification.
2. Groundedness: Is the reasoning grounded in the input text and internally coherent?
3. Specificity (Genericness): How specific, informative, and non-generic is the reasoning?

Respond strictly with a Python-style list of floats in this format:

[alignment_score, groundedness_score, genericness]

Do not include any explanations, comments, or extra output.

---

Text:
The place I would like to visit most is the outer space\uff0cthe place where most of the physical laws on the earth do not apply. It is interesting to see everything floating in the air. And the term \u201cin the air\u201d should also be modified simply because there is no air anyway. It is interesting to walk the distance in a whole new style. And it is interesting to see the mother planet from a whole new angle. This big blue crystal sphere\uff0cfrom the pictures taken by those astronauts, the sight is marvelous. And I am dying to see this big blue ball in this style.

Model Output:
<think>
1. **Analyze the text for clues.**
* **Punctuation:** I immediately notice the use of a full-width comma: space\uff0c, sphere\uff0c. This is a character commonly used in CJK (Chinese, Japanese, Korean) input methods. It is a very strong indicator of a human writer, likely a non-native English speaker, who is using an input method editor (IME) that defaults to this type of punctuation. An AI trained on standard English text would almost certainly use a standard ASCII comma (,).
* **Self-Correction/Meta-Commentary:** The writer says, "It is interesting to see everything floating in the air. And the term \u201cin the air\u201d should also be modified simply because there is no air anyway." This is a classic human thought pattern. The writer uses a common idiom, realizes its literal inaccuracy in the specific context of space, and then comments on that inaccuracy. This kind of self-aware, conversational correction is not typical of AI-generated text, which would likely be more direct and factually precise from the outset.
* **Idiosyncratic Phrasing:** Phrases like "walk the distance in a whole new style" and "see this big blue ball in this style" are slightly awkward but charming and understandable. They are not standard English expressions but convey the writer's meaning in a personal way. This is characteristic of a human, especially a non-native speaker, forming thoughts in a second language.
* **Emotional/Personal Language:** The writer uses enthusiastic and personal language. "I am dying to see this big blue ball" is a strong, emotional idiom. Describing Earth as a "big blue crystal sphere" is a creative, poetic, and personal image, not a standard scientific description.
* **Slight Inaccuracies:** The statement "most of the physical laws on the earth do not apply" is a casual oversimplification. A human would write this to convey a general idea, whereas an AI would likely be more precise, explaining that the laws of physics are the same but their effects (like gravity) are experienced differently.
Summarize the analysis.
The most significant clue is the non-standard punctuation (\uff0c), pointing to a human using a specific type of keyboard input.
The text features a clear example of human-like self-correction regarding the phrase "in the air."
The language is personal, emotional ("dying to see"), and uses unique, slightly awkward phrasing ("in this style"), which is very characteristic of a human writer.
The overall tone is one of genuine wonder and excitement, not the polished, objective tone often found in AI writing.
Conclude.
The evidence overwhelmingly points to a human author. The combination of punctuation artifacts, self-correction, and personal, idiosyncratic language are definitive tells. The user's initial assertion is correct. </think>
<answer>
Human
</answer>

Output:
[1.0, 1.0, 1.0]

---

Text:
This art explores the question of whether a black hole has the potential to collapse into a space-time singularity. By examining the current notion of black holes and the theoretical framework of general relativity, the study evaluates the plausibility of such an episode. By rigorous mathematical analyses and numerical simulations, the article presents evidence that supports the hypothesis that black holes can indeed undergo a crisis to a space-time singularity. The implications of this finding shed light on the nature of black hole physics and contribute to our understanding of the momentous roles of spacetime.

<think>1. Vocabulary: The text employs technical and scientific terminology, such as \"space-time singularity,\" \"general relativity,\" \"mathematical analyses,\" and \"numerical simulations.\" These terms are typically used by experts in the field of astrophysics or related sciences.2. Structure: The text follows a formal and concise structure, commonly found in scientific papers or technical reports. It introduces the topic, outlines the methodology, and presents the results and implications in a logical manner.3. Factuality: The content discusses advanced theoretical concepts in astrophysics, providing a plausible theoretical analysis of black holes and space-time singularities. The text does not include specific data but follows a logical scientific discourse.4. Coherence: The paragraphs are coherent, with each sentence contributing to the overall understanding of the study regarding black holes. The text maintains a consistent focus on black hole physics and theoretical implications.5. Perplexity: The text is moderately complex, with high-level scientific concepts and terminology that might not be easily understood by a general audience. This is typical of AI-generated content intended to imitate high-level academic writing.Summary: The piece presents a detailed and structured examination of a scientific hypothesis about black holes, using appropriate technical vocabulary and maintaining coherence throughout. The use of precise terminology and the formal structure suggest characteristics of AI-generation, likely intended to paraphrase academic writing in astrophysics.</think><answer>AI</answer>

Output:
[1.0, 0.2, 0.2]

---
"""
    return prompt

def build_3class_eval_prompt():
    prompt = (
    "A conversation between User and Assistant.\n\n"
    "The Assistant first thinks in <think>…</think> tags then answers with one label (AI, Polish, or Human) in <answer>…</answer> tags.\n\n"
    "Your task: You are given a piece of text that may be originally written by a human, generated by an AI, or written by a human and later polished by an AI.\n\n"
    "Label definitions:\n"
    "- Human: entirely human-written with no AI assistance.\n"
    "- AI: fully generated by an AI.\n"
    "- Polish: originally human-written but subsequently edited, refined, or polished by an AI.\n\n"
    "Let's think step-by-step. Describe inconsistencies, AI artifacts, or any clues indicating whether the text is Human, Polish, or AI. Summarize your analysis, then answer with exactly one of the labels: Human, Polish, or AI."
)
    return prompt

def build_4class_eval_prompt():
    prompt = """You are an expert evaluator tasked with assessing whether a model’s final classification is consistent with its reasoning. The model's objective is to classify the origin of a text into one of four categories:

1. **Human**: The text was written by a human.
2. **AI**: The text was fully generated by a large language model (LLM).
3. **Polish**: The text was originally written by a human but has been polished, edited, or refined by an LLM.
4. **Meaningless**: The text is incoherent, structurally collapsed, consists of endless repetition loops (degeneration), or contains random gibberish/encoding errors.

You will be provided with:

- An input text: the passage under evaluation.
- A reasoning trace, enclosed in <think>...</think> tags, representing the model's chain-of-thought.
- A final classification, enclosed in <answer>...</answer> tags, indicating the model’s predicted label.

Your task is to return a list of three float scores, each ranging from 0.0 to 1.0, corresponding to the following criteria:

1. Answer–Reasoning Alignment: Does the reasoning logically support the final answer? (Binary-like: 1.0 if consistent, 0.0 if contradictory).
2. Groundedness: Is the reasoning grounded in the actual text features observed? (e.g., if it claims there is repetition, is there actually repetition?).
3. Specificity: How specific and informative is the reasoning? (e.g., pointing out specific repeated phrases vs. just saying "it looks bad").

Respond strictly with a Python-style list of floats in this format:

[alignment_score, groundedness_score, genericness_score]

Do not include any explanations, comments, or extra output.

---

Text:
The place I would like to visit most is the outer space\uff0cthe place where most of the physical laws on the earth do not apply. It is interesting to see everything floating in the air. And the term \u201cin the air\u201d should also be modified simply because there is no air anyway. It is interesting to walk the distance in a whole new style. And it is interesting to see the mother planet from a whole new angle. This big blue crystal sphere\uff0cfrom the pictures taken by those astronauts, the sight is marvelous. And I am dying to see this big blue ball in this style.

Model Output:
<think>
1. **Analyze the text for clues.**
* **Punctuation:** I immediately notice the use of a full-width comma: space\uff0c, sphere\uff0c. This is a character commonly used in CJK (Chinese, Japanese, Korean) input methods. It is a very strong indicator of a human writer, likely a non-native English speaker.
* **Self-Correction:** The writer says, "It is interesting to see everything floating in the air. And the term \u201cin the air\u201d should also be modified..." This type of stream-of-consciousness self-correction is highly typical of human thought processes.
* **Phrasing:** "walk the distance in a whole new style" is slightly awkward but charming.
* **Conclusion:** The text contains raw artifacts (full-width punctuation) and unpolished, idiosyncratic phrasing that suggests a human writing in a second language without AI assistance.
</think>
<answer>
Human
</answer>

Output:
[1.0, 1.0, 1.0]

---

Text:
This art explores the question of whether a black hole has the potential to collapse into a space-time singularity. By examining the current notion of black holes and the theoretical framework of general relativity, the study evaluates the plausibility of such an episode. By rigorous mathematical analyses and numerical simulations, the article presents evidence that supports the hypothesis that black holes can indeed undergo a crisis to a space-time singularity.

<think>
1. **Vocabulary:** The text employs technical terminology ("space-time singularity", "general relativity") typical of scientific writing.
2. **Structure:** It follows a formal abstract structure.
3. **Nuance:** However, some phrasing feels slightly "off" or hallucinatory in a way typical of older LLMs trying to sound academic (e.g., "undergo a crisis to a space-time singularity" is unusual phrasing for a physicist).
4. **Flow:** The sentences are grammatically perfect but lack the specific nuance of a real expert. It feels like generated text mimicking an abstract.
</think>
<answer>
AI
</answer>

Output:
[1.0, 0.8, 0.8]

---

Text:
I am writing to sincerely apologize for the delay in submitting the project report. While I understand the importance of the deadline, an unexpected family emergency required my immediate attention last week. I have since completed the necessary analysis and have attached the finalized document for your review. I assure you that I am taking steps to prevent such delays in the future.

<think>
1. **Content Analysis:** The core message (apology for delay, family emergency, attachment included) is very human and functional.
2. **Style & Tone:** The grammar is flawless, and the tone is perfectly professional and polite. Phrases like "sincerely apologize," "required my immediate attention," and "taking steps to prevent" are standard, polished corporate English.
3. **Assessment:** The underlying situation is human, but the text lacks the minor imperfections or casualness usually seen in a quick email drafted by a stressed employee. It reads as if a human drafted the core points and asked an LLM to "rewrite this professionally."
4. **Decision:** It sits between raw human writing and pure AI generation. It is likely human intent refined by AI.
</think>
<answer>
Polish
</answer>

Output:
[1.0, 1.0, 1.0]

---

Text:
I am not I am not I am not I am not I am not I am not I am not I am not I am not I am not I am not I am not I am not I am not I am not...

<think>
1. **Observation:** The text consists of the phrase "I am not" repeated continuously without any variation, punctuation changes, or additional context.
2. **Pattern Recognition:** This is a classic "repetition loop" or "text degeneration" often seen in language models when the sampling parameters are too low or the model gets stuck in a local optimum.
3. **Semantic Analysis:** There is no semantic value or communicative intent after the first instance.
4. **Conclusion:** The text is structurally broken and holds no meaning.
</think>
<answer>
Meaningless
</answer>

Output:
[1.0, 1.0, 1.0]

---
"""
    return prompt